* Overtone Cheat Sheet 0.9.1
:PROPERTIES:
:ID:       CF18101A-0997-454B-875B-206651F0FF17
:END:
* Overview of examples and source code
[[file:~/Github-repos/overtone-source/src/overtone/examples/][file:~/Github-repos/overtone-source/src/overtone/examples/]]
[[file:~/Github-repos/overtone-source/docs/][file:~/Github-repos/overtone-source/docs/]]
[[file:~/Github-repos/overtone-source/src/overtone/sc/examples/][file:~/Github-repos/overtone-source/src/overtone/sc/examples/]]
* Instruments (need to be manually referred)
** overtone.inst.drum
Drums kick kick2 kick3 kick4 dub-kick dry-kick
small-hat closed-hat close-hat2 open-hat
hat3 soft-hat noise-hat round-kick snare
snare2 noise-snare tone-snare tom clap bing
dance-kick quick-kick haziti-clap
** overtone.inst.piano
Piano piano
** overtone.inst.sampled-piano
Sampled Piano sampled-piano
** overtone.inst.sampler
Sampler granular
** overtone.inst.bass
Bass bass grunge-bass vintage-bass daf-bass
** overtone.inst.synth
Synth ticker ping tb303 mooger rise-fall-pad
pad overpad buzz ks1 ks-stringer fm-demo
harmonic-swimming whoahaha bubbles supersaw
cs80lead simple-flute
** overtone.inst.io
IO mic
* Synths (need to be manually referred)
** overtone.synth.sampled-piano
Sampled Piano sampled-piano
** overtone.synth.stringed
Stringed s guitar
** overtone.synth.ixi
Ixi impulser kick kick2 kick3
** overtone.synth.retro
Retro tb-303
** overtone.synth.sts
STS prophet
* REPL helpers
Documentation
odoc ugen-doc find-ugen find-ugen-doc
Examples
examples example get-example
Shell
ls grep
Synths
unify-synthdef
Pretty Printing
opp pp-synth pp-unified-synth
pp-sc-synth pp-unified-sc-synth
* Timing
Scheduling

Function Application 
now after-delay periodic
interspaced apply-by apply-at

OSC
at

Stopping
stop-player kill-player

Feedback
show-schedule
Metronome

Create
metronome

Manipulate
metro-start metro-tick metro-beat
metro-bpm metro-tock metro-bar metro-bpb
bps beat-ms
* Studio
** Mixer  
*** Control
volume input-gain
** MIDI
*** Connected Controllers
midi-connected-devices
midi-connected-receivers
midi-find-connected-devices
midi-find-connected-device
midi-find-connected-receivers
midi-find-connected-receiver

Info 
midi-device-num
midi-full-device-key

Player
midi-poly-player midi-player-stop
midi-inst-controller

Discovery
midi-capture-next-controller-control-key
midi-capture-next-controller-key

Keys
midi-device-keys
midi-mk-control-key-keyword

State
midi-agent-for-control

Scope
Create & Reset scope pscope spectrogram

Recording
Stop & Start recording-start recording-stop
Query recording?

Inst Effects
Instrument 

inst-volume inst-out-bus inst-fx! clear-fx

FX
fx-noise-gate fx-compressor fx-limiter
fx-sustainer fx-freeverb fx-reverb
fx-echo fx-chorus fx-distortion
fx-distortion2 fx-distortion-tubescreamer
fx-bitcrusher fx-rlpf fx-rhpf fx-feedback
fx-feedback-distortion
* Synth Design
** Design
 definst defsynth
** Examples
 defexamples
** CGens
 defcgen
** Auditioning
 demo run
** Checking
 with-no-ugen-checks with-ugen-debugging
** Arguments
 synth-args synth-arg-index
* Synth Control
** Live Control
 ctl kill
** Node Liveness
 inactive-node-modification-error
inactive-buffer-modification-error
block-node-until-ready?
without-node-blocking
with-inactive-node-modification-error
with-inactive-buffer-modification-error
with-inactive-modification-error
* Event Handling
** Add
 on-event on-sync-event on-latest-event
oneshot-event oneshot-sync-event
** Fire
 event sync-event
** Remove
 remove-event-handler
** Debug
 event-debug-on event-debug-off
event-monitor-on event-monitor-off
event-monitor-timer event-monitor
event-monitor-keys
** Ugen Triggers
 trig-id on-trigger on-latest-trigger
on-sync-trigger
* Nodes & Groups
** Create & Free 
node group node-free group-free
group-clear group-deep-clear
** Manipulate
 node-start node-pause node-place
node-control node-control-range
node-map-controls
node-map-n-controls
group-prepend-node
group-append-node
** Info
 node? node-live? node-loading?
node-active? node-tree
pp-node-tree node-get-control
node-get-controls
** Foundation Groups
 foundation-overtone-group
foundation-output-group
foundation-monitor-group
foundation-input-group
foundation-user-group
foundation-default-group
foundation-safe-group
foundation-safe-pre-default-group
foundation-safe-post-default-group
** Manipulation Handlers
 on-node-destroyed on-node-created
on-node-paused on-node-started
** Event Keys
 node-destroyed-event-key
node-created-event-key
node-paused-event-key
node-started-event-key
* Server
** Startup
 boot-server boot-internal-server
boot-external-server
connect-external-server
** Shutdown
 kill-server
** Control
 stop clear stop-all clear-all
** OSC Communication
 snd recv clear-msg-queue at
snd-immediately
** Diagnostic
 server-status server-info
server-opts server-connected?
server-disconnected?
server-connecting?
internal-server? external-server?
connection-info server-sample-rate
server-num-output-buses
server-num-input-buses
server-num-audio-buses
server-num-buffers
ensure-connected!
** Debug
 sc-osc-log-on sc-osc-log-off
sc-osc-log sc-debug-on
sc-debug-off external-server-log
sc-osc-debug-on sc-osc-debug-off
* Visualisation
Graphviz
Dot Notation
 graphviz
Show PDF
 show-graphviz-synth
* External Assets
Generic URLs
Auto cache & Return Path asset-path asset-seq
asset-bundle-path
asset-bundle-dir
Freesound.org
Playable Function
 freesound
Auto cache & Query
 freesound-info freesound-path
freesound-pack-info
freesound-pack-dir
freesound-search freesound-searchm
freesound-search-paths
* Algorithmic Composition
** Chance
Choice choose choose-n weighted-choose
Dice weighted-coin ranged-rand
** Scaling
Range scale-range
Rounding closest-to round-to
** Trig
Scaled cosr sinr tanr
** Functions
Cycling cycle-fn
** List
Rotation rotate
Creation fill
* Music
** Pitch
Ratios unison octave fifth sixth third fourth
min-third min-sixth
** Note Shifting
shift flat sharp invert inc-first
dec-last
** Notes
note octave-note nth-octave
nth-equal-tempered-freq
canonical-pitch-class-name note-info
mk-midi-string match-note
** Scales
scale resolve-scale scale-field
nth-interval resolve-degree degree->int
degree->interval degrees->pitches
resolve-degree resolve-degrees
interval-freq
** Chords
chord resolve-chord rand-chord
invert-chord chord-degree
** Discovery
find-scale-name find-note-name
find-pitch-class-name find-chord
** Frequencies
cents midi->hz hz->midi
** Amplitude
db->amp
* Sound Data
** Buffers
Create & Free 
buffer buffer-free
buffer-alloc-read
Generate Buffer Data
data->wavetable
create-buffer-data
Read & Write To Server
buffer-read buffer-write!
buffer-write-relay! buffer-fill!
buffer-set! buffer-get
buffer-save buffer-data
buffer-read
Write To Filesystem
write-wav
Streaming In & Out
buffer-stream buffer-stream?
buffer-stream-close buffer-cue
buffer-cue? buffer-cue-pos
buffer-stream-close
Query
buffer? buffer-info?
file-buffer? buffer-out-stream?
buffer-in-stream?
Info
buffer-info num-frames buffer-id
** Samples
Create
load-sample load-samples sample defsample
Playback
mono-player stereo-player
Busses
Create & Free
control-bus audio-bus free-bus
Modify & Read
control-bus-set! control-bus-set-range!
control-bus-get control-bus-get-range
Query
bus? control-bus? audio-bus?
Info
bus-id
Monitor bus-monitor control-bus-monitor
audio-bus-monitor
* Persistence
Local Store
Access
 store-get store-set! store
* CGens
** Audio In
 sound-in
** Buffer Playback
 scaled-play-buf scaled-v-disk
** Control
 hold
** Oscillators
 pm-osc square
** Mix
 mix splay sum
** Pitch
 add-cents
** Tapping
 tap
** Range
 range-lin
* UGen Helper Constants
Done Actions
 NO-ACTION PAUSE FREE FREE-AND-BEFORE
FREE-AND-AFTER FREE-AND-GROUP-BEFORE
FREE-AND-GROUP-AFTER
FREE-UPTO-THIS FREE-FROM-THIS-ON
FREE-PAUSE-BEFORE FREE-PAUSE-AFTER
FREE-AND-GROUP-BEFORE-DEEP
FREE-AND-GROUP-AFTER-DEEP FREE-CHILDREN
FREE-GROUP
FFT Windows
 SINE HANN RECT
Lines
 LINEAR LIN EXPONENTIAL EXP
Onset Analysis
 POWER MAGSUM COMPLEX RCOMPLEX PHASE
WPHASE MKL
Infinity INFINITE INF
* UGen Envelope Helper Functions
env-perc env-triangle env-sine env-lin env-cutoff
env-dadsr env-adsr env-asr
* Unary UGens
neg not-pos? abs ceil floor frac sign squared cubed
sqrt exp reciprocal midicps cpsmidi midiratio
ratiomidi dbamp ampdb octcps cpsoct log log2
log10 sin cos tan asin acos atan sinh cosh tanh
distort softclip rect-window han-window wel-window
tri-window
* Binary UGens
+ - * / mod = not= < > <= >= min max and or xor
round round-up round-down atan2 hypot hypot-aprox
pow ring1 ring2 ring3 ring4 difsqr sumsqr sqrsum
sqrdif absdif thresh amclip scale-neg clip2 excess
fold2 wrap2
* B Equalization Suit UGens
b-low-pass b-hi-pass b-all-pass b-band-pass
b-band-stop b-peak-eq b-low-shelf b-hi-shelf
* Buffer IO UGens
play-buf t-grains buf-rd buf-wr record-buf
scope-out local-buf max-local-bufs set-buf
clear-buf
* Chaos UGens
quad-n quad-l quad-c cusp-n cusp-l gbman-n
gbman-l henon-n henon-l henon-c latoocarfian-n
latoocarfian-l latoocarfian-c lin-cong-n lin-cong-l
lin-cong-c standard-n standard-l fb-sine-n
fb-sine-l fb-sine-c lorenz-l
Compander
amplitude compander normalizer limiter
* Delay UGens
delay1 delay-n delay-l delay-c comb-n comb-l
comb-c allpass-n allpass-l allpass-c buf-delay-n
buf-delay-l buf-delay-c buf-comb-n buf-comb-l
buf-comb-c buf-allpass-n buf-allpass-l
buf-allpass-c
* Demand UGens
demand duty t-duty demand-env-gen dseries dgeom
dbufrd dbufwr dseq dser dshuf drand dxrand dswitch1
dswitch dwhite dbrown dibrown dstutter donce dpoll
* Envelope Ugens
done free-self pause-self free-self-when-done
pause-self-when-done pause free env-gen linen
i-env-gen
* [#A] Fixed Frequency Oscillator UGens
f-sin-osc klang klank blip saw pulse p-sin-grain
* FFT UGens
fft ifft pv-mag-above pv-mag-below pv-mag-clip
pv-local-max pv-mag-smear pv-bin-shift pv-mag-shift
pv-mag-squared pv-mag-noise pv-phase-shift90
pv-phase-shift270 pv-conj pv-phase-shift
pv-brick-wall pv-bin-wipe pv-mag-mul pv-copy-phase
pv-copy pv-max pv-min pv-mul pv-div pv-add
pv-mag-div pv-rand-comb pv-rect-comb pv-rect-comb2
pv-rand-wipe pv-diffuser pv-mag-freeze
pv-bin-scramble fft-trigger
* Extra FFT UGens
pv-conformal-map convolution convolution2
convolution2-l stereo-convolution2-l convolution3
pv-jenson-andersen pv-hainsworth-foote running-sum
* Filter UGens
resonz one-pole one-zero two-pole two-zero apf
integrator decay decay2 lag lag2 lag3 ramp lag-ud
lag2-ud lag3-ud leak-dc rlpf rhpf hpf bpf brf
mid-eq lpz1 lpz2 hpz1 hpz2 slope bpz2 median slew
sos ringz formlet detect-silence
* Grain UGens
grain-sin grain-in warp1
* Information UGens
sample-rate sample-dur radians-per-sample
control-rate control-dur subsample-offset
num-output-busses num-input-busses num-audio-busses
num-control-busses num-buffers num-running-synths
buf-sample-rate buf-rate-scale buf-frames
buf-samples buf-dur buf-channels check-bad-values
poll
* Input UGens
mouse-x mouse-y mouse-button key-state
* IO UGens
disk-out disk-in v-disk-in in local-in lag-in
in-feedback in-trig shared-in out replace-out
offset-out local-out x-out shared-out
* Line Ugens
line x-line lin-exp lin-lin amp-comp amp-comp-a k2a
a2k t2k t2a dc silent
* Machine Listening UGens
beat-track loudness onsets key-track mfcc
beat-track2 spec-flatness spec-pcile spec-centroid
* Miscellaneous UGens (reverb, gendy, et al)
pitch-shift pluck part-conv hilbert freq-shift
g-verb free-verb free-verb2 moog-ff spring ball
t-ball check-bad-values gendy1 gendy2 gendy3
* Noise UGens
white-noise brown-noise pink-noise clip-noise
gray-noise crackle logistic lf-noise0 lf-noise1
lf-noise2 lf-clip-noise lfd-noise0 lfd-noise1
lfd-noise3 ldf-clip-noise hasher mantissa-mask dust
dust2
* [#A] Oscillator UGens
osc sin-osc sin-osc-fb osc-n v-osc v-osc3 c-osc
formant lf-saw lf-par lf-cub lf-tri lf-gauss
lf-pulse var-saw impulse sync-saw wrap-index
index-in-between detect-index shaper degree-to-key
select vibrato index
* Pan UGens
pan2 lin-pan2 pan4 balance2 rotate2 pan-b pan-b2
bi-pan-b2 decode-b2 pan-az x-fade2 lin-x-fade2
* Random UGens
rand-seed rand-id i-rand t-rand ti-rand n-rand
exp-rand t-exp-rand coin-gate lin-rand
* STK UGens
stk-pluck stk-flute stk-bowed stk-mandolin
stk-saxofony stk-shakers stk-banded-wg
stk-voic-form stk-modal-bar stk-clarinet
stk-blow-hole stk-moog stk-bee-three
* Trig UGens
tw-index trig1 trig t-delay send-trig send-reply
latch gate pulse-count set-reset-ff peak
running-min running-max stepper pulse-divider
toggle-ff zero-crossing timer sweep phasor
peak-follower pitch in-range fold clip wrap
schmidt in-rect trapezoid most-changed least-change
last-value
* AY Extra UGens
ay
* BBCut2 Extra UGens
analyse-events2
* Bat Extra UGens
coyote trig-avg w-amp markov-synth frame-compare
needle-rect skip-needle
* Berlach Extra UGens
lpf1 lpfvs6 lpf18 bl-buf-rd clipper4 clipper8
clipper32 soft-clipper4 soft-clipper8
soft-clip-amp4 soft-clip-amp8 os-wrap4 os-wrap8
os-fold4 os-fold8 os-trunc4 os-trunc8 drive-noise
peak-eq2 peak-eq4
* Bhob Extra UGens
henon2-dn henon2-dl henon2-dc henon-trig
gbman2-dn gbman2-dl gbman2-dc gbman-trig
standard2-dn standard2-dl standard2-dc
standard-trig latoocarfian2-dn latoocarfian2-dl
latoocarfian2-dc latoocarfian-trig lorenz2-dn
lorenz2-dl lorenz2-dc lorenz-trig fhn2-dn fhn2-dl
fhn2-dc fhn-trig pv-common-mag pv-common-mul
pv-mag-minus pv-mag-gate pv-compander pv-mag-scale
pv-morph pv-x-fade pv-soft-wipe pv-cutoff
nested-allpass-n nested-allpass-l nested-allpass-c
double-nested-allpass-n double-nested-allpass-l
double-nested-allpass-c moog-ladder rlpfd
streson nl-filt-n nl-filt-l nl-filt-c gauss-trig
lf-brown-noise0 lf-brown-noise1 lf-brown-noise2
t-brown-rand dbrown2 d-gauss t-gauss-rand
t-beta-rand gendy4 gendy5 t-grains2 t-grains3
* Blackrain Extra UGens
amplitude-mod b-moog iir-filter svf
* Distortion Extra UGens
crossover-distortion smooth-decimator sine-shaper
decimator disintegrator
* Glitch Extra UGens
glitch-rhpf glitch-hpf
* Mda Extra UGens
mda-piano
* Membrane Extra UGens
membrane-circle membrane-hexagon
* RFW Extra UGens
switch-delay average-output
* SLU Extra UGens
breakcore brusselator double-well double-well2
double-well3 gravity-grid gravity-grid2
* Stk Extra UGens
stk-pluck stk-flute stk-bowed stk-mandolin
stk-saxofony stk-shakers stk-banded-wg
stk-voic-form stk-modal-bar stk-clarinet
stk-blow-hole stk-moog stk-bee-three
* VOSIM Extra UGens
vosim
Revision: 0.9.1.2, Date: 17th December, 2013
Sam Aaron (sam.aaron gmail com)


* big supercollider vs. overtone doc ugens
** ## SuperCollider 2.0 Unit Generators: 
  
*** ### Unary Operators 
  
neg .. inversion 
reciprocal .. reciprocal 
abs .. absolute value 
floor .. next lower integer 
ceil .. next higher integer 
frac .. fractional part 
sign .. -1 when a < 0, +1 when a > 0, 0 when a is 0 
squared .. a * a 
cubed .. a * a * a 
sqrt .. square root 
exp .. exponential 
midicps .. MIDI note number to cycles per second 
cpsmidi .. cycles per second to MIDI note number 
midiratio .. convert an interval in MIDI notes into a frequency ratio 
ratiomidi .. convert a frequency ratio to an interval in MIDI notes 
dbamp .. decibels to linear amplitude 
ampdb .. linear amplitude to decibels 
octcps .. decimal octaves to cycles per second 
cpsoct .. cycles per second to decimal octaves 
log .. natural logarithm 
log2 .. base 2 logarithm 
log10 .. base 10 logarithm 
sin .. sine 
cos .. cosine 
tan .. tangent 
asin .. arcsine 
acos .. arccosine 
atan .. arctangent 
sinh .. hyperbolic sine 
cosh .. hyperbolic cosine 
tanh .. hyperbolic tangent 
distort .. distortion 
softclip .. distortion 
isPositive .. 1 when a >= 0, else 0 
isNegative .. 1 when a < 0, else 0 
isStrictlyPositive .. 1 when a > 0, else 0 
  
*** ### Binary Operators
  
+ .. addition 
- .. subtraction 
\* .. multiplication 
/ .. division 
% .. float modulo 
\** .. exponentiation 
< .. less than 
<= .. less than or equal 
> .. greater than 
>= .. greater than or equal 
== .. equal 
!= .. not equal 
min .. minimum of two 
max .. maximum of two 
round .. quantization by rounding 
trunc .. quantization by truncation 
atan2 .. arctangent 
hypot .. hypotenuse sqrt(a * a + b * b) 
ring1 .. a * b + a or equivalently: a * (b + 1) 
ring2 .. a * b + a + b 
ring3 .. a * a * b 
ring4 .. a * a * b - a * b * b 
sumsqr .. a * a + b * b 
difsqr .. a * a - b * b 
sqrsum .. (a + b)**2 
sqrdif .. (a - b)**2 
absdif .. fabs(a - b) 
amclip .. two quadrant multiply { 0 when b <= 0, a * b when b > 0 } 
scaleneg .. nonlinear amplification { a when a >= 0, a * b when a < 0 } 
clip2 .. bilateral clipping { b when a > b, -b when a < -b, else a } 
excess .. residual of clipping a - clip2(a,b) 
  
*** ### Oscillators
  
Osc .. wavetable oscillator 
Osc.ar(table, freq, phase, mul, add) 
  
OscN .. noninterpolating wavetable oscillator 
OscN.ar(table, freq, phase, mul, add) 
  
COsc .. chorusing oscillator 
COsc.ar(table, freq, beats, mul, add) 
  
COsc2 .. dual table chorusing oscillator 
COsc2.ar(table1, table2, freq, beats, mul, add) 
  
OscX4 .. 4 table crossfade oscillator 
OscX4.ar(table1, table2, table3, table4, freq, xpos, ypos, mul, add) 
  
SinOsc .. sine table lookup oscillator 
SinOsc.ar(freq, phase, mul, add) 
  
FSinOsc .. very fast sine oscillator 
FSinOsc.ar(freq, mul, add) 
  
Klang .. bank of fixed frequency sine oscillators 
Klang.ar(inSpecificationsArrayRef, iFreqScale, iFreqOffset, mul, add) 
  
PSinGrain .. sine grain with a parabolic envelope (very fast) 
PSinGrain.ar(freq, dur, amp) 
  
Blip .. band limited impulse oscillator 
Blip.ar(freq, numharm, mul, add) 
  
Saw .. band limited sawtooth oscillator 
Saw.ar(freq, mul, add) 
  
Pulse .. band limited pulse wave oscillator 
Pulse.ar(freq, duty, mul, add) 
  
PMOsc .. phase modulation oscillator pair 
PMOsc.ar(carfreq, modfreq, pmindex, modphase, mul, add) 
  
Formant .. formant oscillator 
Formant.ar(fundfreq, formfreq, bwfreq, mul, add) 
  
Phasor .. sawtooth for phase input 
Phasor.ar(freq, mul, add) 
  
LFSaw .. low freq (i.e. not band limited) sawtooth oscillator 
LFSaw.ar(freq, mul, add) 
  
LFPulse .. low freq (i.e. not band limited) pulse wave oscillator 
LFPulse.ar(freq, width, mul, add) 
  
Impulse .. non band limited impulse oscillator 
Impulse.ar(freq, mul, add) 
  
SyncSaw .. hard sync sawtooth wave oscillator 
SyncSaw.ar(syncFreq, sawFreq, mul, add) 
  
*** ### Noise
  
WhiteNoise .. white noise 
WhiteNoise.ar(mul, add) 
  
PinkNoise .. pink noise 
PinkNoise.ar(mul, add) 
  
BrownNoise .. brown noise 
BrownNoise.ar(mul, add) 
  
ClipNoise .. clipped noise 
ClipNoise.ar(mul, add) 
  
LFNoise0 .. low frequency noise, no interpolation 
LFNoise0.ar(freq, mul, add) 
  
LFNoise1 .. low frequency noise, linear interpolation 
LFNoise1.ar(freq, mul, add) 
  
LFNoise2 .. low frequency noise, quadratic interpolation 
LFNoise2.ar(freq, mul, add) 
  
LFClipNoise .. low frequency clipped noise 
LFClipNoise.ar(freq, mul, add) 
  
Crackle .. chaotic noise function 
Crackle.ar(chaosParam, mul, add) 
  
Dust .. random positive impulses 
Dust.ar(density, mul, add) 
  
Dust2 .. random bipolar impulses 
Dust2.ar(density, mul, add) 
  
LinCong .. linear congruential generator 
LinCong.ar(iseed, imul, iadd, imod, mul, add) 
  
Rossler .. chaotic function 
Rossler.ar(chaosParam, dt, mul, add) 
  
Latoocarfian .. Clifford Pickover's chaotic function 
Latoocarfian.ar(a, b, c, d, mul, add) 
  
*** ### Filters
  
FOS .. general first order section 
FOS.ar(in, a0, a1, b1, mul, add) 
  
SOS .. general second order section 
SOS.ar(in, a0, a1, a2, b1, b2, mul, add) 
  
Resonz .. general purpose resonator 
Resonz.ar(in, freq, bwr, mul, add) 
  
Klank .. bank of fixed frequency resonators 
Klank.ar(inSpecificationsArrayRef, iFreqScale, iFreqOffset, iDecayScale, in, mul, add) 
  
OnePole .. one pole filter 
OnePole.ar(in, coef, mul, add) 
  
OneZero .. one zero filter 
OneZero.ar(in, coef, mul, add) 
  
TwoPole .. two pole filter 
TwoPole.ar(in, freq, radius, mul, add) 
  
TwoZero .. two zero filter 
TwoZero.ar(in, freq, radius, mul, add) 
  
RLPF .. resonant low pass filter 
RLPF.ar(in, freq, rq, mul, add) 
  
RHPF .. resonant high pass filter 
RHPF.ar(in, freq, rq, mul, add) 
  
LPF .. Butterworth low pass 
LPF.ar(in, freq, mul, add) 
  
HPF .. Butterworth high pass 
HPF.ar(in, freq, mul, add) 
  
BPF .. Butterworth band pass 
BPF.ar(in, freq, rq, mul, add) 
  
BRF .. Butterworth band reject 
BRF.ar(in, freq, rq, mul, add) 
  
RLPF4 .. fourth order resonant low pass filter 
RLPF4.ar(in, freq, res, mul, add) 
  
Integrator .. integrator 
Integrator.ar(in, coef, mul, add) 
  
Slope .. differentiator scaled by sampling rate 
Slope.ar(in, mul, add) 
  
LeakDC .. removes that ugly DC build up 
LeakDC.ar(in, coef, mul, add) 
  
Decay .. exponential decay 
Decay.ar(in, decayTime, mul, add) 
  
Decay2 .. exponential attack and decay 
Decay2.ar(in, attackTime, decayTime, mul, add) 
  
LPZ1 .. special case: two point sum (one zero low pass) 
LPZ1.ar(in, mul, add) 
  
HPZ1 .. special case: two point difference (one zero high pass) 
HPZ1.ar(in, mul, add) 
  
LPZ2 .. special case: two zero low pass 
LPZ2.ar(in, mul, add) 
  
HPZ2 .. special case: two zero high pass 
HPZ2.ar(in, mul, add) 
  
BPZ2 .. special case: two zero mid pass 
BPZ2.ar(in, mul, add) 
  
BRZ2 .. special case: two zero mid cut 
BRZ2.ar(in, mul, add) 
  
Median .. three point median filter 
Median.ar(in, mul, add) 
  
*** ### Controls
  
ControlIn .. read an external control source 
ControlIn.kr(source, lagTime) 
  
Osc1 .. single shot function generator 
Osc1.ar(table, dur, mul, add) 
  
EnvGen .. break point envelope 
EnvGen.ar(levelArrayRef, durArrayRef, mul, add, levelScale, levelBias, timeScale) 
  
Slew .. slew rate limit 
Slew.ar(in, up, dn, mul, add) 
  
Trig .. timed trigger 
Trig.ar(in, dur) 
  
Trig1 .. timed trigger 
Trig1.ar(in, dur) 
  
TDelay .. trigger delay 
TDelay.ar(in, delayTime) 
  
SetResetFF .. set/reset flip flop 
SetResetFF.ar(set, reset) 
  
ToggleFF .. toggle flip flop 
ToggleFF.ar(trig) 
  
Latch .. sample and hold 
Latch.ar(in, trig) 
  
Gate .. gate or hold 
Gate.ar(in, trig) 
  
Line .. line 
Line.ar(start, end, dur, mul, add) 
  
XLine .. exponential growth/decay 
XLine.ar(start, end, dur, mul, add) 
  
LinExp .. linear range to exponential range conversion 
LinExp.ar(in, srclo, srchi, dstlo, dsthi, mul, add) 
  
PulseCount .. pulse counter 
PulseCount.ar(trig, reset) 
  
PulseDivider .. pulse divider 
PulseDivider.ar(trig, div) 
  
Sequencer .. clocked values 
Sequencer.ar(sequence, clock, mul, add) 
  
ImpulseSequencer .. clocked single sample impulse outputs 
ImpulseSequencer.ar(levelArrayRef, clock, mul, add) 
  
ZeroCrossing .. zero crossing frequency follower 
ZeroCrossing.ar(in) 
  
*** ### Amplitude Operators
  
Compander .. compresser, expander, limiter, gate, ducker 
Compander.ar(input, control, threshold, slopeBelow, slopeAbove, clampTime, relaxTime, mul, add) 
  
Normalizer .. flattens dynamics 
Normalizer.ar(input, level, lookAheadTime) 
  
Limiter .. peak limiter 
Limiter.ar(input, level, lookAheadTime) 
  
Amplitude .. amplitude follower 
Amplitude.ar(input, attackTime, releaseTime, mul, add) 
  
Pan2 .. stereo pan (equal power) 
Pan2.ar(in, pos, level) 
  
Pan4 .. quad pan (equal power) 
Pan4.ar(in, xpos, ypos, level) 
  
PanB .. ambisonic B-format pan 
PanB.ar(in, azimuth, elevation, gain) 
  
LinPan2 .. linear stereo pan 
LinPan2.ar(in, pan) 
  
LinPan4 .. linear quad pan 
LinPan4.ar(in, xpan, ypan) 
  
LinXFade2 .. linear stereo cross fade 
LinXFade2.ar(l, r, pan) 
  
LinXFade4 .. linear quad cross fade 
LinXFade4.ar(lf, rf, lb, rb, xpan, ypan) 
  
*** ### Delays
  
Delay1 .. one sample delay 
Delay1.ar(in, mul, add) 
  
Delay2 .. two sample delay 
Delay2.ar(in, mul, add) 
  
DelayN .. simple delay line, no interpolation 
DelayN.ar(in, maxdtime, delaytime, mul, add) 
  
DelayL .. simple delay line, linear interpolation 
DelayL.ar(in, maxdtime, delaytime, mul, add) 
  
DelayA .. simple delay line, all pass interpolation 
DelayA.ar(in, maxdtime, delaytime, mul, add) 
  
CombN .. comb delay line, no interpolation 
CombN.ar(in, maxdtime, delaytime, decaytime, mul, add) 
  
CombL .. comb delay line, linear interpolation 
CombL.ar(in, maxdtime, delaytime, decaytime, mul, add) 
  
CombA .. comb delay line, all pass interpolation 
CombA.ar(in, maxdtime, delaytime, decaytime, mul, add) 
  
AllpassN .. all pass delay line, no interpolation 
AllpassN.ar(in, maxdtime, delaytime, decaytime, mul, add) 
  
AllpassL .. all pass delay line, linear interpolation 
AllpassL.ar(in, maxdtime, delaytime, decaytime, mul, add) 
  
AllpassA .. all pass delay line, all pass interpolation 
AllpassA.ar(in, maxdtime, delaytime, decaytime, mul, add) 
  
MultiTap .. multi tap delay 
MultiTap.ar(delayTimesArray, levelsArray, in, mul, add) 
  
DelayWr .. write into a delay line 
DelayWr.ar(buffer, in, mul, add) 
  
TapN .. tap a delay line, no interpolation 
TapN.ar(buffer, delaytime, mul, add) 
  
TapL .. tap a delay line, linear interpolation 
TapL.ar(buffer, delaytime, mul, add) 
  
TapA .. tap a delay line, all pass interpolation 
TapA.ar(buffer, delaytime, mul, add) 
  
GrainTap .. granulate a delay line 
GrainTap.ar(buffer, grainDur, pchRatio, pchDispersion, timeDispersion, overlap, mul, add) 
  
PitchShift .. time domain pitch shifter 
PitchShift.ar(in, winSize, pchRatio, pchDispersion, timeDispersion, mul, add) 
  
PingPongN .. ping pong delay, no interpolation 
PingPongN.ar(leftIn, rightIn, maxdtime, delaytime, feedback, mul, add) 
  
PingPongL .. ping pong delay, linear interpolation 
PingPongL.ar(leftIn, rightIn, maxdtime, delaytime, feedback, mul, add) 
  
*** ### Frequency Domain
  
FFT .. fast fourier transform 
FFT.ar(size, offset, cosTable, inputWindow, outputWindow, realInput, imaginaryInput) 
  
IFFT .. inverse fast fourier transform 
IFFT.ar(size, offset, cosTable, inputWindow, outputWindow, realInput, imaginaryInput) 
  
*** ### Samples and I/O
  
PlayBuf .. sample playback from a Signal buffer 
PlayBuf.ar(signal, sigSampleRate, playbackRate, offset, loopstart, loopend, mul, add) 
  
RecordBuf .. record or overdub audio to a Signal buffer 
RecordBuf.ar(buffer, in, recLevel, preLevel, reset, run, loopMode) 
  
AudioIn .. read audio from hardware input 
AudioIn.ar(channelNumber) 
  
DiskIn .. stream audio in from disk file 
DiskIn.ar(soundFile, loopFlag, startFrame, numFrames) 
  
DiskOut .. stream audio out to disk file 
DiskOut.ar(soundFile, numFrames, channelArray) 
  
*** ### Event Spawning
  
Pause .. turn a process on and off 
Pause.ar(eventFunc, level) 
  
Spawn .. timed event generation 
Spawn.ar(eventFunc, numChannels, nextTime, maxRepeats, mul, add) 
  
TSpawn .. signal triggered event generation 
TSpawn.ar(eventFunc, numChannels, maxRepeats, trig, mul, add) 
  
Voicer .. MIDI triggered event generation 
Voicer.ar(eventFunc, numChannels, midiChannel, maxVoices, mul, add) 
  
XFadeTexture .. cross fade events 
XFadeTexture.ar(eventFunc, sustainTime, transitionTime, numChannels, mul, add) 
  
OverlapTexture .. cross fade events 
OverlapTexture.ar(eventFunc, sustainTime, transitionTime, overlap, numChannels, mul, add) 
  
Cycle .. spawn a sequence of events in a cycle 
Cycle.ar(array, numChannels, nextTime, maxRepeats, mul, add) 
  
RandomEvent .. spawn an event at random 
RandomEvent.ar(array, numChannels, nextTime, maxRepeats, mul, add) 
  
SelectEvent .. spawn an event chosen from a list by a function 
SelectEvent.ar(array, selectFunc, numChannels, nextTime, maxRepeats, mul, add) 
  
OrcScore .. play an event list with an orchestra 
OrcScore.ar(orchestra, score, numChannels, nextTime, maxRepeats, mul, add) 
  
*** ### Misc
  
Scope .. write audio to a SignalView 
Scope.ar(signalView, in) 
  
Mix .. mixdown channels in groups 
Mix.ar(channelsArray) 
  
K2A .. control rate to audio rate converter 
K2A.ar(in) 
  
Sink .. takes any number of inputs and outputs zero. Can be used to force execution order. 
Sink.ar(theInputArray) 
  
OutputProxy .. used as an output place holder by Spawners and Panners, etc. 
There is no reason for a user to create an OutputProxy directly. 

